version: "3.8"
services:
  backend:
    build: ./Server
    ports:
      - "8000:8000"
    env_file:
      - ./Server/.env
    volumes:
      - ./Server:/app
    restart: always
  frontend:
    build: ./Client
    ports:
      - "5173:5173"
    volumes:
      - ./Client:/app
    restart: always
